#!/usr/bin/env node
// CLI: parses the three AML bulk XML ZIPs and builds JSON + Markdown indexes.
// Run after fetch-data: npm run build-index
//
// This file is the thin I/O wrapper. The parsing/section-building core lives in
// scripts/lib/build-corpus.js (importable + unit-tested via test/build-smoke.test.js);
// the ordered-tree extraction helpers live in scripts/lib/extract-text.js.
//
// Parsing note (fix #3, 2026-06): we parse with `preserveOrder: true` so that
// inline cross-reference elements (<LINK>, <CHARFORMAT>) stay in document order
// relative to the surrounding running text. In the default (non-ordered) mode a
// node's direct text collapsed into a single "#text" and child elements were
// grouped by tag, so extractText() emitted all the running text first and then
// appended the inline elements — relocating spelled-out section numbers to the
// end of the sentence and running adjacent words together ("sectionof").

import AdmZip from "adm-zip";
import { writeFileSync, mkdirSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { makeParser } from "./lib/extract-text.js";
import {
  extractVersion,
  collectSections,
  findDocument,
} from "./lib/build-corpus.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, "..", "data");
const RAW_DIR = join(DATA_DIR, "raw");
const JSON_DIR = join(DATA_DIR, "index", "json");
const MD_DIR = join(DATA_DIR, "index", "markdown");

mkdirSync(JSON_DIR, { recursive: true });
mkdirSync(MD_DIR, { recursive: true });

const CORPORA = [
  { key: "charter", zip: "charter.zip", xmlDir: "XML" },
  { key: "admin_code", zip: "admin_code.zip", xmlDir: "XML" },
  { key: "rules", zip: "rules.zip", xmlDir: "XML" },
];

const parser = makeParser();

const versions = {};

for (const corpus of CORPORA) {
  const zipPath = join(RAW_DIR, corpus.zip);
  if (!existsSync(zipPath)) {
    console.error(`Missing ${zipPath} — run npm run fetch-data first.`);
    continue;
  }

  console.log(`\nParsing ${corpus.key}...`);
  const zip = new AdmZip(zipPath);
  const entries = zip.getEntries().filter(
    (e) => e.entryName.startsWith(`${corpus.xmlDir}/`) && e.entryName.endsWith(".xml")
  );

  console.log(`  Found ${entries.length} XML files`);

  let version = "Unknown";
  const sections = [];
  let fileCount = 0;

  for (const entry of entries) {
    const xml = entry.getData().toString("utf8").replace(/^﻿/, ""); // strip BOM
    let parsed;
    try {
      parsed = parser.parse(xml);
    } catch (e) {
      console.warn(`  Skipping ${entry.entryName}: ${e.message}`);
      continue;
    }

    // Extract version from root file.
    if (entry.entryName.endsWith("0-0-0-1.xml")) {
      version = extractVersion(parsed);
      console.log(`  Version: ${version}`);
    }

    collectSections(findDocument(parsed), corpus.key, sections);
    fileCount++;
    if (fileCount % 50 === 0) process.stdout.write(`  Parsed ${fileCount}/${entries.length} files...\r`);
  }

  console.log(`  Indexed ${sections.length} sections from ${fileCount} files`);

  versions[corpus.key] = {
    currentThrough: version,
    indexedAt: new Date().toISOString(),
    sectionCount: sections.length,
  };

  // Write JSON index.
  writeFileSync(
    join(JSON_DIR, `${corpus.key}.json`),
    JSON.stringify(sections, null, 2)
  );
  console.log(`  Saved data/index/json/${corpus.key}.json`);

  // Write Markdown index — one file per corpus, one section per heading.
  const corpusLabel = {
    charter: "NYC Charter",
    admin_code: "NYC Administrative Code",
    rules: "Rules of the City of New York",
  }[corpus.key];

  const md = [
    `# ${corpusLabel}`,
    ``,
    `> ${version}`,
    ``,
    `_${sections.length} sections indexed. Generated by [nyc-charter-laws-rules](https://github.com/BetaNYC/nyc-charter-laws-rules)._`,
    ``,
    `---`,
    ``,
    ...sections.map((s) =>
      [
        `## ${s.heading}`,
        ``,
        `**Citation:** ${s.citation}`,
        ``,
        s.text || "_No text extracted._",
        ``,
        `---`,
        ``,
      ].join("\n")
    ),
  ].join("\n");

  writeFileSync(join(MD_DIR, `${corpus.key}.md`), md);
  console.log(`  Saved data/index/markdown/${corpus.key}.md`);
}

writeFileSync(join(JSON_DIR, "versions.json"), JSON.stringify(versions, null, 2));
console.log("\nVersions saved to data/index/versions.json:");
console.log(JSON.stringify(versions, null, 2));
console.log("\nIndex build complete.");
